package edu.cmu.cs.lti.ark.fn.identification.training;

import gnu.trove.THashMap;
import gnu.trove.THashSet;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;

/**
 * Created by alessio on 22/12/15.
 */

public class ReadDataStructures {

    public static Object readFromFile(String fileName) throws IOException, ClassNotFoundException {
        ObjectInputStream in = new ObjectInputStream(new FileInputStream(new File(fileName)));
        Object ret = in.readObject();
        in.close();

        return ret;
    }

    /**
     * Read data structures generated by {@link CreateDataStructures}
     * <p>
     * Arguments:
     * - FrameNet map
     * - Frame element map
     *
     * @param args Arguments (see above)
     */
    public static void main(String[] args) {
        String frameMapFile = args[0];
        String elementMapFile = args[1];
        String frame = args[2];

        try {
            THashMap<String, THashSet<String>> frameMap = (THashMap<String, THashSet<String>>) readFromFile(
                    frameMapFile);
            THashMap<String, THashSet<String>> elementMap = (THashMap<String, THashSet<String>>) readFromFile(
                    elementMapFile);


            THashSet<String> set1 = frameMap.get(frame);
            THashSet<String> set2 = elementMap.get(frame);

            if (set1 != null) {
                System.out.println(set1);
            }
            if (set2 != null) {
                System.out.println(set2);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
